src/Application/Common/Entity/Serie.php
<?php

namespace App\Application\Common\Entity;


use Doctrine\Common\Collections\Collection;

interface Serie
{
    /**
     * @return string|null
     */
    public function getId(): ?string;

    /**
     * @param string|null $id
     * @return Serie
     */
    public function setId(?string $id): Serie;

    /**
     * @return string|null
     */
    public function getTitle(): ?string;

    /**
     * @param string|null $title
     * @return Serie
     */
    public function setTitle(?string $title): Serie;

    /**
     * @return array|null
     */
    public function getAlias(): ?array;

    /**
     * @return string
     */
    public function getSlug(): string;

    /**
     * @param string $slug
     * @return Serie
     */
    public function setSlug(string $slug): Serie;

    /**
     * @param array|null $alias
     * @return Serie
     */
    public function setAlias(?array $alias): Serie;

    /**
     * @return array|null
     */
    public function getImages(): ?array;

    /**
     * @param array|null $images
     * @return Serie
     */
    public function setImages(?array $images): Serie;

    /**
     * @return string|null
     */
    public function getYear(): ?string;

    /**
     * @param string|null $year
     * @return Serie
     */
    public function setYear(?string $year): Serie;

    /**
     * @return string|null
     */
    public function getOrigin(): ?string;

    /**
     * @param string|null $origin
     * @return Serie
     */
    public function setOrigin(?string $origin): Serie;

    /**
     * @return array|null
     */
    public function getGenre(): ?array;

    /**
     * @param array|null $genre
     * @return Serie
     */
    public function setGenre(?array $genre): Serie;

    /**
     * @return string|null
     */
    public function getNumberOfSeasons(): ?string;

    /**
     * @param string|null $numberOfSeasons
     * @return Serie
     */
    public function setNumberOfSeasons(?string $numberOfSeasons): Serie;

    /**
     * @return array|null
     */
    public function getSeasonsDetails(): ?array;

    /**
     * @param array|null $seasonsDetails
     * @return Serie
     */
    public function setSeasonsDetails(?array $seasonsDetails): Serie;

    /**
     * @return string|null
     */
    public function getNumberOfEpisodes(): ?string;

    /**
     * @param string|null $numberOfEpisodes
     * @return Serie
     */
    public function setNumberOfEpisodes(?string $numberOfEpisodes): Serie;

    /**
     * @return string|null
     */
    public function getLastEpisode(): ?string;

    /**
     * @param string|null $lastEpisode
     * @return Serie
     */
    public function setLastEpisode(?string $lastEpisode): Serie;

    /**
     * @return string|null
     */
    public function getDescription(): ?string;

    /**
     * @param string|null $description
     * @return Serie
     */
    public function setDescription(?string $description): Serie;

    /**
     * @return array|null
     */
    public function getNote(): ?array;

    /**
     * @param array|null $note
     * @return Serie
     */
    public function setNote(?array $note): Serie;

    /**
     * @return string|null
     */
    public function getStatus(): ?string;

    /**
     * @param string|null $status
     * @return Serie
     */
    public function setStatus(?string $status): Serie;

    /**
     * @return string|null
     */
    public function getSerieShow(): ?string;

    /**
     * @param string|null $serieShow
     * @return Serie
     */
    public function setSerieShow(?string $serieShow): Serie;

    /**
     * @return \DateTime
     */
    public function getUpdatedAt(): \DateTime;


    /**
     * @param mixed $updatedAt
     * @return Serie
     */
    public function setUpdatedAt($updatedAt): Serie;


    /**
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime;


    /**
     * @param mixed $createdAt
     * @return Serie
     */
    public function setCreatedAt($createdAt);


    /**
     * @return @var bool
     */
    public function getSeen(): bool;


    /**
     * @param bool $seen
     * @return Serie
     */
    public function setSeen($seen): Serie;


    /**
     * @return Collection|Season[]
     */
    public function getSeasons(): Collection;


    /**
     * @param Season $season
     * @return Serie
     */
    public function addSeasons(Season $season): Serie;


    /**
     * @param Season $season
     * @return Serie
     */
    public function removeSeasons(Season $season): Serie;

    /**
     * @return Collection|Episode[]
     */
    public function getEpisodes(): Collection;

    /**
     * @param Episode $episode
     * @return Serie
     */
    public function addEpisodes(Episode $episode): Serie;

    /**
     * @param Episode $episode
     * @return Serie
     */
    public function removeEpisodes(Episode $episode): Serie;

    /**
     * @return string
     */
    public function __toString(): string;
    /**
     * @return Collection|Favorite[]
     */
    public function getFavorites(): Collection;

    /**
     * @param Favorite $favorite
     * @return Serie
     */
    public function addFavorite(Favorite $favorite): Serie;

    /**
     * @param Favorite $favorite
     * @return Serie
     */
    public function removeFavorite(Favorite $favorite): Serie;
}

templates/serie/_seasons_details.html.twig
<div class="card mb-4">
    <div class="card-body">
        <div class="list-group ">
            {% for season in serieDetails.seasons %}
                <div class="list-group-item list-group-item-warning list-serie">
                <a href="#" class="list-group-item-warning display-4 ">
                    {{ 'home.season' | trans }} {{ season.0.seasonNumber }}
                </a>
                {% if is_granted('ROLE_USER') %}
                    <a class="btn btn-link js-seasons-seens"
                       href={{ path('set.season.seen.status', {
                        'serieId': serieDetails.serieId.0,
                        'seasonNumber': season.0.seasonNumber,
                    }) }}
                    >
                        {% if season.0.seasonSeen == 'episode.seeAll'|trans %}
                            <i class="fas fa-times js-season-seens js-season-seens-{{ season.0.seasonNumber }}" >{{ season.0.seasonSeen }}</i>
                        {% else %}
                            <i class="fas fa-check js-season-seens js-season-seens-{{ season.0.seasonNumber }}">{{ season.0.seasonSeen }}</i>
                        {% endif %}
                    </a>
                {% endif %}
                    {% for episode in season %}
                        <div class="list-group-item
                                {% if episode.episode is divisible by(2) %}list-group-item-light
                                {% else %}list-group-item-info
                                {% endif %}
                                list-episode">
                        <a href={{ path('episode.show', {
                                'episodeNumber': episode.episode,
                                'serieId': serieDetails.serieId.0,
                                'seasonNumber': episode.season
                           }) }}
                        >
                            {{ 'home.episode' | trans }} {{ episode.episode }}
                        </a>
                        {% if is_granted('ROLE_USER') %}
                            <a class="btn btn-link js-seens" href={{ path('set.episode.seen.status', {
                                'episodeNumber': episode.episode,
                                'serieId': serieDetails.serieId.0,
                                'seasonNumber': episode.season
                            }) }}
                                >
                                {% if episode.seen ==  'episode.toSee' | trans %}
                                    <i class="fas fa-times js-seen js-seen-{{ episode.season }}">{{ episode.seen }}</i>
                                {% else %}
                                    <i class="fas fa-check js-seen js-seen-{{ episode.season }}"> {{ episode.seen }}</i>
                                {% endif %}
                            </a>
                        {% endif %}
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>
</div>

templates/serie/_serie.html.twig
<div class="card mb-4">
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ serie.serieShow }}">{{ serie.title }}</a>
        </h5>
        <img src="{{ serie.images.show }}" alt="card-img-top" style="width: 100%; height:auto;">
        <div id="description">
            <p class="card-text" id="collapseDescription">{{ serie.description }}</p>
        </div>
        <div class="text-primary">{{ 'serie.seasonsNumber' | trans }} : {{ serie.numberOfSeasons }}</div>
        <div class="text-primary">{{ 'serie.episodeNumber' | trans }} : {{ serie.numberOfEpisodes }}</div>
        {% if is_granted('ROLE_USER') %}
            <div class="text-primary">{{ 'serie.lastEpisode' | trans }} : {{ serie.lastEpisode }}</div>
            <a class="js-toggle-favorites" href={{ path('toggle.favorite', {'id': serie.id}) }}>
                <span class="js-toggle-favorite js-toggle-favorite btn
                    {% if serie.isfavorite == false %}
                        btn-primary
                    {% else %}
                        btn-danger
                    {% endif %}"
                >
                    {% if serie.isfavorite == false %}
                        {{ 'serie.addToFavorite' | trans }}
                    {% else %}
                        {{ 'serie.removeFromFaforite' | trans }}
                    {% endif %}
                </span>
            </a>
        {%  endif %}
    </div>
</div>